name: Generate blinking text animation

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
    - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Create README with blinking text
        run: |
          echo '<!DOCTYPE html><html><head><title>Blinking Text</title></head><body><h1><blink>Your Name</blink></h1></body></html>' > README.md
          git config --global user.email "yogayatajugnu@gmail.com"
          git config --global user.name "Yogayata Verma"
          git add README.md
          git commit -m "Add blinking text to README"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
